apiVersion: v1
kind: Namespace
metadata:
  name: cloud
---
apiVersion: v1
kind: Secret
metadata:
  namespace: cloud
  name: mariadb-secret
stringData:
  rootpassword: INSERT_PASSWORD_HERE
  userpassword: INSERT_PASSWORD_HERE

